"""
LangGraph ReAct Agent Implementation for Meridian Data Copilot.
Features a state machine with a self-correction error loop for SQL syntax errors,
multi-hop tool orchestration, and full reasoning trace recording.
"""

import os
import json
import time
from typing import Annotated, Any, Dict, List, Optional, TypedDict
from langchain_core.messages import (
    AIMessage,
    BaseMessage,
    HumanMessage,
    SystemMessage,
    ToolMessage,
)
from langgraph.graph import END, StateGraph
from langgraph.graph.message import add_messages

from src.config import GROQ_API_KEY, GROQ_MODEL, MAX_AGENT_ITERATIONS
from src.prompts import build_system_message
from src.tools import MERIDIAN_TOOLS, execute_sql_query, search_company_documents, create_data_chart
from src.charts import generate_chart


class MeridianState(TypedDict):
    """LangGraph Agent State representation."""
    messages: Annotated[List[BaseMessage], add_messages]
    tool_history: List[Dict[str, Any]]
    chart_figures: List[Dict[str, Any]]
    iteration: int
    sql_retries: int


def get_llm(api_key: Optional[str] = None, model_name: Optional[str] = None):
    """
    Initializes and returns the configured ChatGroq instance bound with tools.
    Defaults to openai/gpt-oss-120b, with support for openai/gpt-oss-20b and qwen/qwen3.8-27b.
    """
    key = api_key or os.getenv("GROQ_API_KEY") or GROQ_API_KEY
    model = model_name or os.getenv("GROQ_MODEL") or GROQ_MODEL or "openai/gpt-oss-120b"
    if not key:
        return None
    try:
        from langchain_groq import ChatGroq
        llm = ChatGroq(
            model=model,
            api_key=key,
            temperature=0.1,
            max_tokens=2048,
        )
        return llm.bind_tools(MERIDIAN_TOOLS)
    except Exception as e:
        print(f"[Agent] Error initializing ChatGroq: {e}")
        return None


def reasoner_node(state: MeridianState) -> Dict[str, Any]:
    """
    Reasoner Node: Inspects user input, chat history, and tool feedback to decide next action.
    Includes proactive TPM rate limit protection and automatic model fallback.
    """
    messages = state["messages"]
    iteration = state.get("iteration", 0) + 1
    llm = get_llm()

    # Prepend or ensure SystemMessage is at the start
    if not any(isinstance(m, SystemMessage) for m in messages):
        sys_msg = SystemMessage(content=build_system_message())
        messages_to_send = [sys_msg] + messages
    else:
        messages_to_send = messages

    if llm is None:
        fallback_msg = _generate_fallback_response(state)
        return {
            "messages": [fallback_msg],
            "iteration": iteration,
        }

    try:
        response = llm.invoke(messages_to_send)
        return {
            "messages": [response],
            "iteration": iteration,
        }
    except Exception as e:
        err_str = str(e)
        if "413" in err_str or "rate_limit_exceeded" in err_str or "TPM" in err_str:
            print("[Agent] Groq rate limit hit. Attempting automatic fallback to openai/gpt-oss-20b...")
            fallback_llm = get_llm(model_name="openai/gpt-oss-20b")
            if fallback_llm:
                try:
                    response = fallback_llm.invoke(messages_to_send)
                    return {
                        "messages": [response],
                        "iteration": iteration,
                    }
                except Exception as retry_err:
                    err_str = str(retry_err)

        err_msg = AIMessage(
            content=f"An error occurred while communicating with the reasoning model: {err_str}."
        )
        return {
            "messages": [err_msg],
            "iteration": iteration,
        }


def tool_executor_node(state: MeridianState) -> Dict[str, Any]:
    """
    Tool Executor Node: Executes tool calls generated by the reasoner,
    handles errors for self-correction, prevents duplicate query loops, and records traces.
    """
    last_msg = state["messages"][-1]
    if not hasattr(last_msg, "tool_calls") or not last_msg.tool_calls:
        return {}

    tool_map = {
        "execute_sql_query": execute_sql_query,
        "search_company_documents": search_company_documents,
        "create_data_chart": create_data_chart,
    }

    tool_history = list(state.get("tool_history", []))
    chart_figures = list(state.get("chart_figures", []))
    tool_messages = []
    sql_retries = state.get("sql_retries", 0)

    for tc in last_msg.tool_calls:
        tool_name = tc.get("name")
        tool_args = tc.get("args", {})
        tool_id = tc.get("id", f"call_{len(tool_history)}")
        
        start_time = time.time()
        tool_fn = tool_map.get(tool_name)
        
        # Anti-loop check: prevent calling identical query back-to-back
        is_duplicate = any(
            h.get("tool") == tool_name and h.get("args") == tool_args
            for h in tool_history[-2:]
        )

        if is_duplicate:
            output_str = "Notice: Duplicate query already executed. Please synthesize your final response using previous results."
            status = "skipped_duplicate"
        elif tool_fn is None:
            output_str = f"Error: Tool '{tool_name}' is not recognized."
            status = "error"
        else:
            try:
                raw_output = tool_fn.invoke(tool_args)
                output_str = str(raw_output)
                status = "success"
                
                if tool_name == "execute_sql_query" and '"success":false' in output_str.lower():
                    status = "sql_error"
                    sql_retries += 1
                
                if tool_name == "create_data_chart" and "data" in tool_args:
                    c_res = generate_chart(
                        data=tool_args["data"],
                        chart_type=tool_args.get("chart_type", "bar"),
                        x_col=tool_args.get("x_col"),
                        y_col=tool_args.get("y_col"),
                        title=tool_args.get("title", "Stellantis Commercial Analytics"),
                    )
                    if c_res.get("success") and c_res.get("figure"):
                        chart_figures.append(c_res)

            except Exception as e:
                output_str = f"Tool execution failed with exception: {str(e)}"
                status = "error"

        duration = round(time.time() - start_time, 3)

        tool_history.append({
            "tool": tool_name,
            "args": tool_args,
            "output": output_str,
            "status": status,
            "duration_sec": duration,
        })

        tool_messages.append(
            ToolMessage(
                content=output_str,
                tool_call_id=tool_id,
                name=tool_name,
            )
        )

    return {
        "messages": tool_messages,
        "tool_history": tool_history,
        "chart_figures": chart_figures,
        "sql_retries": sql_retries,
    }


def route_next(state: MeridianState) -> str:
    """Conditional Edge: Decides whether to execute tools or terminate."""
    last_msg = state["messages"][-1]
    iteration = state.get("iteration", 0)

    if iteration >= MAX_AGENT_ITERATIONS:
        return END

    if hasattr(last_msg, "tool_calls") and len(last_msg.tool_calls) > 0:
        return "tool_executor"

    return END


def create_meridian_graph():
    """
    Builds and compiles the LangGraph StateGraph.
    Workflow: User Query -> Reasoner -> (tool_calls?) -> Tool Executor -> Reasoner -> Final Answer
    """
    workflow = StateGraph(MeridianState)

    workflow.add_node("reasoner", reasoner_node)
    workflow.add_node("tool_executor", tool_executor_node)

    workflow.set_entry_point("reasoner")
    workflow.add_conditional_edges("reasoner", route_next, {
        "tool_executor": "tool_executor",
        END: END
    })
    workflow.add_edge("tool_executor", "reasoner")

    return workflow.compile()


meridian_graph = create_meridian_graph()


def _generate_fallback_response(state: MeridianState) -> AIMessage:
    """Fallback if no GROQ_API_KEY is configured."""
    return AIMessage(
        content="Please provide a valid GROQ_API_KEY in your .env file to enable reasoning."
    )
